[DO NOT USE THIS COMMIT] Patch error in script

diff --git a/scripts/tctst b/scripts/tctst
--- a/scripts/tctst
+++ b/scripts/tctst
@@ -48,7 +48,7 @@ while [ : ]; do
             if [[ $2 == "model" ]] || [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
                 DESIGN=$2
                 OUTNAME=$2.out;
-            else 
+            else
                 echo -e "Error: Unknown design '$2'. Fatal." | tee error.log
                 echo -e "For help do 'tctst --help'.";
                 exit 10;
@@ -116,6 +116,8 @@ rm ${DESIGN}_${TESTNAME}tmp
 
 if diff -q emu_${TESTNAME}.trace ${DESIGN}_${TESTNAME}.trace ; then
     echo -e "${DESIGN} design passed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
-else echo -e "${DESIGN} design failed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
+    exit 0;
+else
+    echo -e "${DESIGN} design failed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
+    exit 14;
 fi
-exit 0
