new and improved tctst file

diff --git a/scripts/tctst b/scripts/tctst
--- a/scripts/tctst
+++ b/scripts/tctst
@@ -3,83 +3,86 @@
 ASM=../prog/asm/asm
 EMU=../prog/emu/emu
 TEST_DIR=../prog/src/
-if [[ -n $1 ]]; then
-    if [[ $1 == "-h" ]]; then
-        echo -e "This script supports --design option, -h option and -dbg, When run using no options, it would display basic function and method of usage of the script. The -h option provides detailed use cases of the script. The --design should be followed by a valid test source code name. Valid indicating that it should be present in the ../prog/src/ directory. There are 3 cases of --design namely beh, str, str74. In the case of --design=beh would indicate the script to test the behavioural model, --design=str would indicate the structural mode and --design=str74 would indicate the structural in 74 series model. The -dbg option is to enable RAM debug, the output of the same getting stored in the trace files. When -dbg option is used, the design wouldnt be compared against emulator (god reference design).
-\nExample usage is ../scripts/tctst --design=str src_code.s \n                 ../scripts/tctst --design=str -dbg src_code.s";
-    else
-        if [[ -n $2 ]] ; then
-            if [[ $2 == "-dbg" ]]; then
-                TESTNAME=$3;
-                OUTNAME=beh_dbg.out;
-                DBG=1;
-            else TESTNAME=$2;
-                 OUTNAME=beh.out;
-                 DBG=0;
-            fi
-        else echo "invalid option value, retry with correct value";
-        fi
-        case $1 in
-            "--design=beh")
-                if test -e $TEST_DIR$TESTNAME ; then
-                    $ASM $TEST_DIR$TESTNAME -o bin.out
-                    $EMU bin.out > emu.trace
-
-                    ../prog/bin2readmemh/bin2readmemh bin.out > program.mem
-                    make $OUTNAME -f ../scripts/makefile 2> beherrorlog
-                    if grep -qi -e "error" -e "stop" -e "no such" -e "unable" beherrorlog ; then
-                        echo "Compilation Error detected, test failed, see beherrorlog file for more details, please solve this issue and retry";
-                        exit 5;
-                    fi
-                    vvp $OUTNAME -vcd beh.vcd > behtmp
-                    tail -n +2 behtmp > beh.trace
-                    if [[ $DBG == 1 ]]; then
-                        exit 0;
-                    fi
-                    if diff -q emu.trace beh.trace ; then
-                        echo "behavioural passed "$TESTNAME" test";
-                        echo "behavioural passed "$TESTNAME" test" > beh_$TESTNAME.log;
-                    else "behavioural failed "$TESTNAME" test";
-                    fi;
-                else echo "Invalid Test name, please try again with a valid test";
-                fi;;
-            "--design=str")
-                if [[ -n $2 ]] ; then
-                    if [[ $2 == "-dbg" ]]; then
-                        TESTNAME=$3;
-                        OUTNAME=str_dbg.out;
-                        DBG=1;
-                    else TESTNAME=$2;
-                         OUTNAME=str.out;
-                         DBG=0;
-                    fi
-                else echo "invalid option value, retry with correct value";
-                fi
-                if test -e $TEST_DIR$TESTNAME ; then
-                    $ASM $TEST_DIR$TESTNAME -o bin.out
-                    $EMU bin.out > emu.trace
-
-                    ../prog/bin2readmemh/bin2readmemh bin.out > program.mem
-                    make str.out -f ../scripts/makefile 2> strerrorlog
-                    if grep -qi -e "error" -e "stop" -e "no such" -e "unable" strerrorlog ; then
-                        echo "Compilation Error detected, test failed, see strerrorlog file for more details, please solve this issue and retry";
-                        exit 5;
-                    fi
-                    vvp str.out -vcd beh.vcd > strtmp
-                    tail -n +2 strtmp > str.trace
-                    if [[ $DBG == 1 ]]; then
-                        exit 0;
-                    fi
-                    if diff -s emu.trace str.trace ; then
-                        echo "structural passed "$TESTNAME" test";
-                        echo "structural passed "$TESTNAME" test" > str_$TESTNAME.log;
-                    else "structural failed "$TESTNAME" test";
-                    fi;
-                else echo "Invalid Test name, please try again with a valid test";
-                fi;;
-            "--design=str74")echo "Structural74 is work in progress try a different option";;
-            *)echo "invalid option, supported --design option values are beh, str and str74";;
-        esac;
-    fi;
-else echo "This script generates log files for both the emulator and behavioural models and compares them against each other to measure correctness for a particular test, the first argument provided should be the test code file that is present in the ../prog/src/ directory, use -h option to know more.";
+DBG=""
+TRACE=""
+DESIGN=""
+exec 2> error.log
+VALID_ARGS=$(getopt --options d:Dh --long design:,DEBUG,help -- "$@")
+if [[ -s error.log ]] ; then                       #-s returns true if file exists with size greater than zero otherwise false
+    echo -e "error.log is non empty, hence error has occured in getopt\nstage, fatal.";
+    exit ;
+else echo -e "error.log is empty hence no error has occured in getopt\nstage, continuing";
 fi
+
+eval set -- "$VALID_ARGS"
+while [ : ]; do
+    case "$1" in
+	-d | --design)
+	    if [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
+		DESIGN=$2
+		OUTNAME=$2.out;
+		echo -e "$DESIGN $OUTNAME";
+	    else echo -e "The above value '$2' for --design/-d option is invalid,\nuse -h or --help to know more about the option --design values";
+		 echo -e "test failed due to invalid design name.\nTest+Design specific log file not produced.\nFatal." > error.log
+		 exit 10;
+	    fi
+            shift 2
+            ;;
+	-D | --DEBUG)
+            DBG="_dbg.";
+            shift
+            ;;
+	-h | --help)
+            echo "help in progress"
+            shift
+            ;;
+	--) shift; 
+            break 
+            ;;
+    esac
+done
+if [[ $DBG == "" ]] ; then
+    DBG="." ;
+fi
+echo $DBG
+OUTNAME=$(gawk -F '.' --assign dbg=$DBG '{ print ($1 dbg $2) }' <<< $OUTNAME)
+echo -e "$OUTNAME"
+if [[ -s $TEST_DIR$1 ]]; then
+    echo -e "test name is valid and exists in ../prog/src/ directory";
+else echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ directory.\nFatal";
+     echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ directory.\nFatal" > error.log;
+     exit 11;
+fi
+TESTNAME=$1
+$ASM $TEST_DIR$TESTNAME -o bin.out | tee error.log
+TESTNAME=$(gawk -F '.' '{ print $1}' <<< $TESTNAME)
+if [[ -s error.log ]]; then
+    echo -e "Error: $TESTNAME test contains errors, please refer to specs doc\nand correct the issue.\nFatal";
+    exit 12;
+else echo -e "$TESTNAME test code contains no errors, proceeding to next step.";
+     #echo -e "Error: test contains errors, please refer to specs doc\nand correct the issue.\nFatal" > error.log;
+fi
+$EMU bin.out > emu_${TESTNAME}.trace
+../prog/bin2readmemh/bin2readmemh bin.out > program.mem
+make $OUTNAME -f ../scripts/makefile
+vvp $OUTNAME > ${DESIGN}_${TESTNAME}tmp
+tail -n +2 ${DESIGN}_${TESTNAME}tmp > ${DESIGN}_${TESTNAME}.trace
+rm ${DESIGN}_${TESTNAME}tmp
+echo -e "${DESIGN}_${TESTNAME}.trace"
+if [[ $DBG == "_dbg." ]] ; then
+    echo -e "debug option enabled, simulation stopped, debug values\nin ${DESIGN}_${TESTNAME}.trace file"
+    exit 0;
+fi
+echo "diff -q emu_${TESTNAME}.trace ${DESIGN}_${TESTNAME}.trace"
+if diff -q emu_${TESTNAME}.trace ${DESIGN}_${TESTNAME}.trace ; then
+    echo -e "${DESIGN} design passed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
+else echo -e "${DESIGN} design failed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
+fi
+exit 0
+#         echo -e "This script supports --design option, -h option and -dbg, When run using no options, it would display basic function and method of usage of the script. The -h option provides detailed use cases of the script. The --design should be followed by a valid test source code name. Valid indicating that it should be present in the ../prog/src/ directory. There are 3 cases of --design namely beh, str, str74. In the case of --design=beh would indicate the script to test the behavioural model, --design=str would indicate the structural mode and --design=str74 would indicate the structural in 74 series model. The -dbg option is to enable RAM debug, the output of the same getting stored in the trace files. When -dbg option is used, the design wouldnt be compared against emulator (god reference design).
+# \nExample usage is ../scripts/tctst --design=str src_code.s \n                 ../scripts/tctst --design=str -dbg src_code.s";
+#echo -e "This script generates log files for both the emulator and behavioural\n
+#            models and compares them against each other to measure correctness for a\n
+# 	   particular test, the first argument provided should be the test code file that\n
+# 	   is present in the ../prog/src/ directory, use -h option to know more.";
+# 
