Fixed some messages, added comments, added a sleep timer for make

diff --git a/scripts/tctst b/scripts/tctst
--- a/scripts/tctst
+++ b/scripts/tctst
@@ -2,23 +2,41 @@
 
 ASM=../prog/asm/asm
 EMU=../prog/emu/emu
-TEST_DIR=../prog/src/
+TEST_DIR=../prog/src
 DBG=""
 TRACE=""
 DESIGN=""
-BRIEF_HELP="A simple tool that tests and compares results of emu design against either one of the 3 (beh, str or str74) and provides a short report on the same. Use '-h' (--help long form) option to know more about 'tctst' tool."
-FILL80=| fold -w 80 -s
+USAGE="Usage: tctst [options] testname\n\
+       For details do 'tctst -h'"
+BRIEF_HELP="A simple tool that tests and compares results of emu \
+design against either one of the 3 (beh, str or str74) \
+and provides a short report on the same. \
+Use '-h' (--help long form) option to know more about \
+'tctst' tool."
+
+##FILL80=| fold -w 80 -s
+
+#-------------------------------------------------------------------------------
+# If no args, print usage message and exit
+#-------------------------------------------------------------------------------
 if [[ $1 == "" ]] ; then
-    printf "%-80s\n" "${BRIEF_HELP}" | fold -w 80 -s;
-    exit 0;
+    printf "${USAGE}\n"
+#    printf "${BRIEF_HELP}\n" | fold -w 80 -s;
+    exit 1; # Error exit
 fi
 
+# Redirect stderr to error.log
 exec 2> error.log
-VALID_ARGS=$(getopt --options d:Dh --long design:,DEBUG,help -- "$@")
 
-if [[ -s error.log ]] ; then                       #-s returns true if file exists with size greater than zero otherwise false
-    echo -e "error.log is non empty, hence error has occured in getopt\nstage, fatal.";
-    exit ;
+#-------------------------------------------------------------------------------
+# Parse command line arguments
+#-------------------------------------------------------------------------------
+VALID_ARGS=$(getopt --options d:Dh --long design:,debug,help -- "$@")
+
+if [[ -s error.log ]] ; then   #-s returns true if file exists with size greater than zero otherwise false
+    echo `cat error.log | sed -e s/getopt/Error/g`
+    echo "For help do 'tctst --help'"
+    exit 1;
 # else echo -e "error.log is empty hence no error has occured in getopt stage, continuing." | fold -w 80 -s;
 fi
 
@@ -29,18 +47,19 @@ while [ : ]; do
             if [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
                 DESIGN=$2
                 OUTNAME=$2.out;
-            else echo -e "The above value '$2' for --design/-d option is invalid,\nuse -h or --help to know more about the option --design values.";
-                 echo -e "Error: test failed due to invalid design name.\nTest+Design specific log file not produced.\nFatal." > error.log
-                 exit 10;
+            else 
+                echo -e "Error: Unknown design '$2'. Fatal." | tee error.log
+                echo -e "For help do 'tctst --help'.";
+                exit 10;
             fi
             shift 2
             ;;
-        -D | --DEBUG)
+        -D | --debug)
             DBG="_dbg.";
             shift
             ;;
         -h | --help)
-            echo -e "The use of the script is in the following format - \n../scripts/tctst [option] [option_with argument] argument testname.\nThe script supports 3 options:-\n\n -h (--help) option provides detailed methods of using the tool.If -h option (an argument-less option) is used, then no testname is allowed.\n\n -D (--DEBUG long format) - This option enables the debug mode in the SRAM  module, the debug messages (SRAM I/O values) are stored in 'design'_'testname'.trace file.\n\n -d (--design long format) - This option requires an argument that must be one of the following three choices\n a) beh - Behavioural Model\n b) str - Structural Model\n c) str74 - Structural in 74 Model\nIn absence of -h (--help) option, a testfile should be provided which is present in the directory ../prog/src/ and should be an Assembly code file adhering to Instruction Format specified in specs doc." | fold -w 80 -s
+            echo -e "The use of the script is in the following format - \n../scripts/tctst [option] [option_with argument] argument testname.\nThe script supports 3 options:-\n\n -h (--help) option provides detailed methods of using the tool.If -h option (an argument-less option) is used, then no testname is allowed.\n\n -D (--debug long format) - This option enables the debug mode in the SRAM  module, the debug messages (SRAM I/O values) are stored in 'design'_'testname'.trace file.\n\n -d (--design long format) - This option requires an argument that must be one of the following three choices\n a) beh - Behavioural Model\n b) str - Structural Model\n c) str74 - Structural in 74 Model\nIn absence of -h (--help) option, a testfile should be provided which is present in the directory ../prog/src/ and should be an Assembly code file adhering to Instruction Format specified in specs doc." | fold -w 80 -s
             exit 0;
             shift
             ;;
@@ -56,7 +75,7 @@ fi
 
 OUTNAME=$(gawk -F '.' --assign dbg=$DBG '{ print ($1 dbg $2) }' <<< $OUTNAME)
 
-if [[ -s $TEST_DIR$1 ]]; then
+if [[ -s $TEST_DIR/$1 ]]; then
     echo -e "Test name is valid and exists in ../prog/src/ directory";
 else echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ directory.\nFatal";
      echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ directory.\nFatal" > error.log;
@@ -64,7 +83,7 @@ else echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ dir
 fi
 
 TESTNAME=$1
-$ASM $TEST_DIR$TESTNAME -o bin.out | tee error.log
+$ASM $TEST_DIR/$TESTNAME -o bin.out | tee error.log
 TESTNAME=$(gawk -F '.' '{ print $1}' <<< $TESTNAME)
 
 if [[ -s error.log ]]; then
@@ -77,7 +96,8 @@ rm -f debug.trace
 
 $EMU bin.out > emu_${TESTNAME}.trace
 ../prog/bin2readmemh/bin2readmemh bin.out > program.mem
-make $OUTNAME -f ../scripts/makefile
+sleep 0.2
+make $OUTNAME --makefile=../scripts/makefile
 
 if [[ -s error.log ]]; then
     echo -e "Error: Makefile reported an error, check error.log file for more details.\nFatal";
