debug option doesnt omit diffing now

diff --git a/scripts/tctst b/scripts/tctst
--- a/scripts/tctst
+++ b/scripts/tctst
@@ -6,15 +6,16 @@ TEST_DIR=../prog/src/
 DBG=""
 TRACE=""
 DESIGN=""
-BRIEF_HELP="A simple tool that tests and compares results of emu design against either one of the 3 (beh, str or str74) and provides a short report on the same. Use '-h' (--help long form) option to know more about 'tctst' tool." 
+BRIEF_HELP="A simple tool that tests and compares results of emu design against either one of the 3 (beh, str or str74) and provides a short report on the same. Use '-h' (--help long form) option to know more about 'tctst' tool."
 FILL80=| fold -w 80 -s
 if [[ $1 == "" ]] ; then
     printf "%-80s\n" "${BRIEF_HELP}" | fold -w 80 -s;
     exit 0;
 fi
-    
+
 exec 2> error.log
 VALID_ARGS=$(getopt --options d:Dh --long design:,DEBUG,help -- "$@")
+echo "$VALID_ARGS"
 if [[ -s error.log ]] ; then                       #-s returns true if file exists with size greater than zero otherwise false
     echo -e "error.log is non empty, hence error has occured in getopt\nstage, fatal.";
     exit ;
@@ -24,27 +25,27 @@ fi
 eval set -- "$VALID_ARGS"
 while [ : ]; do
     case "$1" in
-	-d | --design)
-	    if [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
-		DESIGN=$2
-		OUTNAME=$2.out;
-	    else echo -e "The above value '$2' for --design/-d option is invalid,\nuse -h or --help to know more about the option --design values.";
-		 echo -e "Error: test failed due to invalid design name.\nTest+Design specific log file not produced.\nFatal." > error.log
-		 exit 10;
-	    fi
+        -d | --design)
+            if [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
+                DESIGN=$2
+                OUTNAME=$2.out;
+            else echo -e "The above value '$2' for --design/-d option is invalid,\nuse -h or --help to know more about the option --design values.";
+                 echo -e "Error: test failed due to invalid design name.\nTest+Design specific log file not produced.\nFatal." > error.log
+                 exit 10;
+            fi
             shift 2
             ;;
-	-D | --DEBUG)
+        -D | --DEBUG)
             DBG="_dbg.";
             shift
             ;;
-	-h | --help)
+        -h | --help)
             echo -e "The use of the script is in the following format - \n../scripts/tctst [option] [option_with argument] argument testname.\nThe script supports 3 options:-\n\n -h (--help) option provides detailed methods of using the tool.If -h option (an argument-less option) is used, then no testname is allowed.\n\n -D (--DEBUG long format) - This option enables the debug mode in the SRAM  module, the debug messages (SRAM I/O values) are stored in 'design'_'testname'.trace file.\n\n -d (--design long format) - This option requires an argument that must be one of the following three choices\n a) beh - Behavioural Model\n b) str - Structural Model\n c) str74 - Structural in 74 Model\nIn absence of -h (--help) option, a testfile should be provided which is present in the directory ../prog/src/ and should be an Assembly code file adhering to Instruction Format specified in specs doc." | fold -w 80 -s
-	    exit 0;
+            exit 0;
             shift
             ;;
-	--) shift; 
-            break 
+        --) shift;
+            break
             ;;
     esac
 done
@@ -66,16 +67,17 @@ if [[ -s error.log ]]; then
     exit 12;
 else echo -e "$TESTNAME test code contains no errors, proceeding to next step.";
 fi
+rm -f debug.trace
 $EMU bin.out > emu_${TESTNAME}.trace
 ../prog/bin2readmemh/bin2readmemh bin.out > program.mem
 make $OUTNAME -f ../scripts/makefile
 vvp $OUTNAME > ${DESIGN}_${TESTNAME}tmp
 tail -n +2 ${DESIGN}_${TESTNAME}tmp > ${DESIGN}_${TESTNAME}.trace
 rm ${DESIGN}_${TESTNAME}tmp
-if [[ $DBG == "_dbg." ]] ; then
-    echo -e "Debug option enabled, script stopped, debug values\nin ${DESIGN}_${TESTNAME}.trace file"
-    exit 0;
-fi
+# if [[ $DBG == "_dbg." ]] ; then
+#     echo -e "Debug option enabled, script stopped, debug values\nin ${DESIGN}_${TESTNAME}.trace file"
+#     exit 0;
+# fi
 if diff -q emu_${TESTNAME}.trace ${DESIGN}_${TESTNAME}.trace ; then
     echo -e "${DESIGN} design passed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
 else echo -e "${DESIGN} design failed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
